language: python
cache: pip
services: mongodb
branches:
  only:
    - master
python:
  - "2.7"
before_install:
    - sudo apt-get update -qq
    # Start X for selenium tests.
    - "export DISPLAY=:99.0"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    - sleep 3
install:
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
script:
  - python manage.py test
notifications:
  irc:
    channels: "irc.freenode.org#ghiro"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
