language: python
cache: pip
services: mongodb
branches:
  only:
    - master
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
before_install:
    - export PIP_USE_MIRRORS=true
    - sudo apt-get update -qq
    # Linear algebra (Scipy deps).
    - sudo apt-get install libblas-dev liblapack-dev

    # Start X for selenium tests.
    - "export DISPLAY=:99.0"
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
    - sleep 3
install:
  # Upgrade pip.
  - pip install --upgrade pip
  # Deps.
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install coveralls
script:
  - coverage run --source='.' manage.py test
after_success:
  coveralls
notifications:
  irc:
    channels: "irc.freenode.org#ghiro"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
